# -*- coding: utf-8 -*-

# Max-Planck-Gesellschaft zur Förderung der Wissenschaften e.V. (MPG) is
# holder of all proprietary rights on this computer program.
# You can only use this computer program if you have closed
# a license agreement with MPG or you get the right to use the computer
# program from someone who is authorized to grant you that right.
# Any use of the computer program without a valid license is prohibited and
# liable to prosecution.
#
# Copyright©2019 Max-Planck-Gesellschaft zur Förderung
# der Wissenschaften e.V. (MPG). acting on behalf of its Max Planck Institute
# for Intelligent Systems and the Max Planck Institute for Biological
# Cybernetics. All rights reserved.
#
# Contact: ps-license@tuebingen.mpg.de

from __future__ import absolute_import
from __future__ import print_function
from __future__ import division

import sys
import os

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
SMPLX_PACKAGE_DIR = os.path.abspath(os.path.join(ROOT_DIR, 'smplx', 'smplx'))

if SMPLX_PACKAGE_DIR not in sys.path:
    sys.path.insert(0, SMPLX_PACKAGE_DIR)
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

import os.path as osp

import time
import yaml
import torch

import smplx
from smplx.smplx.body_models import create

from smplifyx.utils import JointMapper
from smplifyx.cmd_parser import parse_config
from smplifyx.data_parser import create_dataset
from smplifyx.fit_single_frame import fit_single_frame

from smplifyx.camera import create_camera
from smplifyx.prior import create_prior
from OpenPose.detect_keypoints import OpenPoseKeypointConverter
torch.backends.cudnn.enabled = False


def main(**args):
    output_folder = args.pop('output_folder')
    output_folder = osp.expandvars(output_folder)
    if not osp.exists(output_folder):
        os.makedirs(output_folder)

    # Store the arguments for the current experiment
    conf_fn = osp.join(output_folder, 'conf.yaml')
    with open(conf_fn, 'w') as conf_file:
        yaml.dump(args, conf_file)

    result_folder = args.pop('result_folder', 'results')
    result_folder = osp.join(output_folder, result_folder)
    if not osp.exists(result_folder):
        os.makedirs(result_folder)

    mesh_folder = args.pop('mesh_folder', 'meshes')
    mesh_folder = osp.join(output_folder, mesh_folder)
    if not osp.exists(mesh_folder):
        os.makedirs(mesh_folder)

    out_img_folder = osp.join(output_folder, 'images')
    if not osp.exists(out_img_folder):
        os.makedirs(out_img_folder)

    float_dtype = args['float_dtype']
    if float_dtype == 'float64':
        dtype = torch.float64
    elif float_dtype == 'float32':
        dtype = torch.float64
    else:
        print('Unknown float type {}, exiting!'.format(float_dtype))
        sys.exit(-1)

    use_cuda = args.get('use_cuda', True)
    if use_cuda and not torch.cuda.is_available():
        print('CUDA is not available, exiting!')
        sys.exit(-1)

    img_folder = args.pop('img_folder', 'images')

    data_folder = args.get('data_folder')
    if data_folder is None:
        raise KeyError('data_folder is required in args')

    # Detect keypoints and scores from images and save as json format in data_folder/keypoints
    # converter = OpenPoseKeypointConverter()
    # converter.detect_n_save(data_folder)

    # create dataset object here
    dataset_obj = create_dataset(img_folder=img_folder, **args)  #data_parser.OpenPose object 
    start = time.time()

    input_gender = args.pop('gender', 'neutral')
    gender_lbl_type = args.pop('gender_lbl_type', 'none')
    max_persons = args.pop('max_persons', -1)

    float_dtype = args.get('float_dtype', 'float32')
    if float_dtype == 'float64':
        dtype = torch.float64
    elif float_dtype == 'float32':
        dtype = torch.float32
    else:
        raise ValueError('Unknown float type {}, exiting!'.format(float_dtype))
    '''
    `JointMapper` is a utility class in SMPLify-X that **reorders and selects the joints generated by the SMPL-X body model so that they match the joint ordering of the input 
    keypoint detector (such as OpenPose)**. This is necessary because SMPL-X and OpenPose use different joint definitions and indexing schemes. For example, OpenPose may assign 
    index 0 to the nose, whereas SMPL-X may assign index 0 to the pelvis. Without a mapping, the optimization would compare incorrect body parts (e.g., nose with pelvis), resulting 
    in meaningless reprojection errors. The mapping is obtained using `dataset_obj.get_model2data()`, which internally calls `smpl_to_openpose()` to generate the correspondence between
    SMPL-X joints and OpenPose joints based on the selected body model and keypoint format. The mapping is stored as a **non-trainable buffer** using `register_buffer()`, ensuring it is 
    automatically moved to the appropriate device (CPU/GPU) and saved with the model without being optimized. During the forward pass, `JointMapper` uses `torch.index_select()` to efficiently 
    select and reorder the SMPL-X joints according to this mapping. The reordered joints are then projected onto the image plane and compared with the detected 2D keypoints to compute the
    reprojection loss, which guides the optimization of the SMPL-X body parameters. Thus, `JointMapper` serves as the bridge between the SMPL-X body model and the external keypoint
    detector, ensuring that corresponding anatomical joints are correctly aligned throughout the fitting process.

    dataset_obj.get_model2data() --> ponts to the function smpl_to_openpose() in utils.py, which returns the indices of the permutation that maps OpenPose keypoints to SMPL-X keypoints. This mapping is 
    used by JointMapper to reorder the joints output by the SMPL-X model so that they correspond to the detected keypoints from OpenPose. Without this mapping, the optimization would compare mismatched joints 
    (e.g., comparing a hand joint with a foot joint), leading to incorrect fitting results. By ensuring that the SMPL-X joints are aligned with the detected keypoints, JointMapper enables accurate computation of reprojection errors and effective optimization of the body model parameters.
    '''
    joint_mapper = JointMapper(dataset_obj.get_model2data())  #JointMapper object
    '''
    The "model_params" dictionary serves as a central configuration object for constructing the SMPL-X model. It specifies which body parameters should exist (body pose, 
    shape, hands, face, eyes, jaw, etc.), how the model should interact with the detected keypoints (through joint_mapper), where to load the pretrained model from, and 
    what numerical precision to use. The use of **args makes the initialization flexible: any additional configuration options supplied through the experiment's YAML file
    or command-line arguments are automatically forwarded to smplx.create() without requiring the source code to be updated each time a new option is introduced. This pattern 
    is common in configurable machine learning code because it keeps the initialization concise while remaining extensible.'''
    model_params = dict(model_path=args.get('model_folder'),
                        joint_mapper=joint_mapper,
                        create_global_orient=True,
                        create_body_pose=not args.get('use_vposer'),
                        create_betas=True,
                        create_left_hand_pose=True,
                        create_right_hand_pose=True,
                        create_expression=True,
                        create_jaw_pose=True,
                        create_leye_pose=True,
                        create_reye_pose=True,
                        create_transl=False,
                        dtype=dtype,
                        **args)

    ''' 
    smplx.create(gender='male', **model_params) --> This line creates an instance of the SMPL-X body model for male. 
    The model parameters are defined in the model_params dictionary, which includes the path to the pretrained model,
      the joint mapping to align SMPL-X joints with detected keypoints, and flags indicating which body parts to include 
      (e.g., body pose, shape, hands, face, eyes, jaw). The **args allows additional configuration options to be passed 
      in dynamically
    '''
    
    male_model = create(gender='male', **model_params)
    
    # SMPL-H has no gender-neutral model
    if args.get('model_type') != 'smplh':
        neutral_model = create(gender='neutral', **model_params)
    female_model = create(gender='female', **model_params)

    # Create the camera object
    focal_length = args.get('focal_length')
    camera = create_camera(focal_length_x=focal_length,
                           focal_length_y=focal_length,
                           dtype=dtype,
                           **args)

    if hasattr(camera, 'rotation'):
        camera.rotation.requires_grad = False

    use_hands = args.get('use_hands', True)
    use_face = args.get('use_face', True)
    
 

#==================================================================================
# Creates the body pose prior (regularizer) used in the SMPLify-X loss.
# Type is set by args['body_prior_type'] (e.g. 'gmm' = pretrained Gaussian
# Mixture Model over mocap poses, 'l2' = simple L2 penalty toward T-pose).
# Penalizes anatomically implausible poses during optimization; if VPoser
# is enabled instead, this prior plays a secondary role for the body.
    body_pose_prior = create_prior(
        prior_type=args.get('body_prior_type'),
        dtype=dtype,
        **args)

    jaw_prior, expr_prior = None, None
    if use_face:
        jaw_prior = create_prior(
            prior_type=args.get('jaw_prior_type'),
            dtype=dtype,
            **args)
        expr_prior = create_prior(
            prior_type=args.get('expr_prior_type', 'l2'),
            dtype=dtype, **args)

    left_hand_prior, right_hand_prior = None, None
    if use_hands:
        lhand_args = args.copy()
        lhand_args['num_gaussians'] = args.get('num_pca_comps')
        left_hand_prior = create_prior(
            prior_type=args.get('left_hand_prior_type'),
            dtype=dtype,
            use_left_hand=True,
            **lhand_args)

        rhand_args = args.copy()
        rhand_args['num_gaussians'] = args.get('num_pca_comps')
        right_hand_prior = create_prior(
            prior_type=args.get('right_hand_prior_type'),
            dtype=dtype,
            use_right_hand=True,
            **rhand_args)

    shape_prior = create_prior(
        prior_type=args.get('shape_prior_type', 'l2'),
        dtype=dtype, **args)

    angle_prior = create_prior(prior_type='angle', dtype=dtype)
    if use_cuda and torch.cuda.is_available():
        device = torch.device('cuda')

        camera = camera.to(device=device)
        female_model = female_model.to(device=device)
        male_model = male_model.to(device=device)
        if args.get('model_type') != 'smplh':
            neutral_model = neutral_model.to(device=device)
        body_pose_prior = body_pose_prior.to(device=device)
        angle_prior = angle_prior.to(device=device)
        shape_prior = shape_prior.to(device=device)
        if use_face:
            expr_prior = expr_prior.to(device=device)
            jaw_prior = jaw_prior.to(device=device)
        if use_hands:
            left_hand_prior = left_hand_prior.to(device=device)
            right_hand_prior = right_hand_prior.to(device=device)
    else:
        device = torch.device('cpu')

    # A weight for every joint of the model and send it to device
    joint_weights = dataset_obj.get_joint_weights().to(device=device,
                                                       dtype=dtype)
    # Add a fake batch dimension for broadcasting
    joint_weights.unsqueeze_(dim=0)
#======================================================================================
    
    for idx, data in enumerate(dataset_obj):
        """
        data = {
        'fn': fn,                      # filename (string), e.g. 'frame_0001'
        'img': img,                    # the actual image, as a numpy array (H, W, 3)
        'keypoints': keypoints,        # 2D keypoints from OpenPose, shape (num_people, num_joints, 3)}
        """
        
        # ======================================:):):):):):):):):)==============================================
        img = data['img']
        fn = data['fn']
        keypoints = data['keypoints']
        print('Processing: {}'.format(data['img_path']))

        curr_result_folder = osp.join(result_folder, fn)
        if not osp.exists(curr_result_folder):
            os.makedirs(curr_result_folder)
        curr_mesh_folder = osp.join(mesh_folder, fn)
        if not osp.exists(curr_mesh_folder):
            os.makedirs(curr_mesh_folder)
        for person_id in range(keypoints.shape[0]):
            if person_id >= max_persons and max_persons > 0:
                continue

            curr_result_fn = osp.join(curr_result_folder,
                                      '{:03d}.pkl'.format(person_id))
            curr_mesh_fn = osp.join(curr_mesh_folder,
                                    '{:03d}.obj'.format(person_id))

            curr_img_folder = osp.join(output_folder, 'images', fn,
                                       '{:03d}'.format(person_id))
            if not osp.exists(curr_img_folder):
                os.makedirs(curr_img_folder)

            if gender_lbl_type != 'none':
                if gender_lbl_type == 'pd' and 'gender_pd' in data:
                    gender = data['gender_pd'][person_id]
                if gender_lbl_type == 'gt' and 'gender_gt' in data:
                    gender = data['gender_gt'][person_id]
            else:
                gender = input_gender

            if gender == 'neutral':
                body_model = neutral_model
            elif gender == 'female':
                body_model = female_model
            elif gender == 'male':
                body_model = male_model

            out_img_fn = osp.join(curr_img_folder, 'output.png')

            fit_single_frame(img, keypoints[[person_id]],
                             body_model=body_model,
                             camera=camera,
                             joint_weights=joint_weights,
                             dtype=dtype,
                             output_folder=output_folder,
                             result_folder=curr_result_folder,
                             out_img_fn=out_img_fn,
                             result_fn=curr_result_fn,
                             mesh_fn=curr_mesh_fn,
                             shape_prior=shape_prior,
                             expr_prior=expr_prior,
                             body_pose_prior=body_pose_prior,
                             left_hand_prior=left_hand_prior,
                             right_hand_prior=right_hand_prior,
                             jaw_prior=jaw_prior,
                             angle_prior=angle_prior,
                             **args)

    elapsed = time.time() - start
    time_msg = time.strftime('%H hours, %M minutes, %S seconds',
                             time.gmtime(elapsed))
    print('Processing the data took: {}'.format(time_msg))


if __name__ == "__main__":
    args = parse_config()
    main(**args)
